FROM python:3.11
WORKDIR /app
RUN apt-get update && apt-get install -y netcat-openbsd dos2unix
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . /app/
RUN dos2unix entrypoint.sh && chmod +x entrypoint.sh
EXPOSE 8000
ENTRYPOINT ["bash", "entrypoint.sh"]
