FROM python:3.11
WORKDIR /app
COPY  requirements.txt .
RUN apt-get update && apt-get install -y libpq-dev gcc
RUN pip install --no-cache-dir -r requirements.txt
COPY . /app/
RUN chmod +x serial_runs.sh
CMD [ "bash" ,"serial_runs.sh"]